"""alter review model, remove rating_id col

Revision ID: 0778fcfd9c80
Revises: 5a8ed1b3213a
Create Date: 2025-02-08 10:50:49.280584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0778fcfd9c80'
down_revision: Union[str, None] = '5a8ed1b3213a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reviews_rating_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'rating_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reviews_rating_id_fkey', 'reviews', 'ratings', ['rating_id'], ['id'])
    # ### end Alembic commands ###
