"""Alter User table. is_activae -> default=True_v2

Revision ID: 52b092c5285c
Revises: 88c62de34604
Create Date: 2025-02-05 18:18:44.514257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b092c5285c'
down_revision: Union[str, None] = '88c62de34604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
