"""Alter User table. is_suplier -> is_supplier

Revision ID: c5b968f306f9
Revises: 5a13c2d11caf
Create Date: 2025-02-05 18:00:04.028050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b968f306f9'
down_revision: Union[str, None] = '5a13c2d11caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_supplier', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_suplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_suplier', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_supplier')
    # ### end Alembic commands ###
