"""alter review model, add... rating_id col

Revision ID: dad34f596ef3
Revises: 0778fcfd9c80
Create Date: 2025-02-08 11:52:59.027037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad34f596ef3'
down_revision: Union[str, None] = '0778fcfd9c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'ratings', ['rating_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'rating_id')
    # ### end Alembic commands ###
