"""alter review model, alter ratings(single_parent)=true

Revision ID: f7950d6ec703
Revises: dad34f596ef3
Create Date: 2025-02-08 11:56:45.373401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7950d6ec703'
down_revision: Union[str, None] = 'dad34f596ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
